[akesi]
address = "10.1.1.1"
publicKey = "rJ91zWvjJwj5ByxLx1tiyiRR3m8qRmZ4sQm7RctSTlc="
endpoint = "akesi.ppom.me:58234"
listenPort = 58234

[musi]
address = "10.1.1.2"
publicKey = "/Tcl/+rIl3OVZXyLUz9e3hhHKJdhFspEbwztQzT0mFg="
endpoint = "musi.ppom.me:58234"
listenPort = 58234
preferred = true

[sona]
address = "10.1.1.3"
publicKey = "UYjsvFMCc+yRBPxX4rHiuRx1jQd1WntClaAueNXNmh4="
listenPort = 58234

[kili]
address = "10.1.1.4"
publicKey = "uJe+eUQNQD59DYYTUXnqsqQGen/5W3KmjfjZk5hqR0g="
listenPort = 58234

[poki]
address = "10.1.1.5"
publicKey = "q/pcH81V8mv6NeLaESu9Wbh0E5iEs+/NRu4Ow0/88UI="
listenPort = 58234

[lipu]
address = "10.1.1.6"
publicKey = "/5qQfgqM6GsgmdLFpE+TDzTAqXupoMhSShNAo9kkkRM="
listenPort = 58234

[marvin]
address = "10.1.1.7"
publicKey = "KtYzUxAsqkx3hR3oPl0s+MSYm1jJgcqBnuWvknFx9kI="
