# Create & network to reach host                            ↓ host ip on the network
# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 mynet
# containers on this network will access to the host, for example to connect to a database
{ lib, pkgs, config, ... }:
let
  json = pkgs.formats.json {};
  directusName = name: "directus-${name}";
  varLib = name: "/var/lib/${directusName name}";
in {
  options.services.directus = with lib; with types; {
    enable = mkEnableOption "Enable Directus using impure npm";

    version = mkOption {
      type = str;
      description = "Directus version to use";
    };

    servers = mkOption {
      default = {};
      description = "Configuration of multiple directus instances";
      type = attrsOf (submodule ({config, name, ...}@args: {
        options = {

          useLocalStorage = mkOption {
            type = bool;
            default = true;
            description = mdDoc ''
              Whether to use local storage for file uploads
            '';
          };

          settings = mkOption {
            type = json.type;
            default = {};
            description = mdDoc ''
              Settings passed to Directus. A config.json file is generated by Nix.

              Setting a value to null will remove it from the config.json
              For example, to override DB_* settings to local postgresql:
              ```nix
              {
                DB_FILENAME = null; # remove DB_FILENAME default-coded value
                DB_CLIENT = "postgres";
                DB_HOST = "localhost";
                DB_PORT = config.services.postgresql.port;
              }
              ```

              See [upstream doc](https://docs.directus.io/self-hosted/config-options.html) for supported options.

              Some options mentionned in this doc are also used by this module (activation script, nginx, redis etc.).
              Changing them also changes related configuration.
            '';
            type = submodule {
              freeformType = (attrsOf (nullOr (oneOf [str int bool]))) // { description = "settings option"; };
              options = {
                # General
                HOST = mkOption {
                  type = str;
                  default = if instanceCfg.nginx.enable then "127.0.0.1" else "0.0.0.0";
                  defaultText = literalExpression ''if services.directus.<name>.nginx.enable then "127.0.0.1" else "0.0.0.0"'';
                  description = mdDoc ''
                    IP or host the API listens on
                  '';
                };
                PORT = mkOption {
                  type = port;
                  default = 8055;
                  description = mdDoc ''
                    The port Directus will run on
                  '';
                };
                PUBLIC_URL = mkOption {
                  type = str;
                  default = "/";
                  description = mdDoc ''
                    The URL where your API can be reached on the web. It is also used for things like OAuth redirects,
                    forgot-password emails, and logos that needs to be publicly available on the internet.
                  '';
                };
                SERVE_APP = mkOption {
                  type = str;
                  default = !instanceCfg.nginx.enable;
                  defaultText = literalExpression ''!services.directus.<name>.nginx.enable'';
                  description = mdDoc ''
                    Whether or not to serve the Admin App under /admin.
                  '';
                };

                # Database
                DB_CLIENT = mkOption {
                  type = enum ["postgres", "mysql", "oracledb", "mssql", "sqlite3", "cockroachdb"];
                  default = "sqlite3";
                  description = mdDoc ''
                    What database client to use.
                  '';
                };
                DB_FILENAME = mkOption {
                  type = str;
                  default = if instanceCfg.settings.DB_CLIENT == "sqlite3"
                  then "/var/lib/directus-${name}/data.db"
                  else null;
                  defaultText = literalExpression ''
                    if services.directus.<name>.settings.DB_CLIENT == "sqlite3"
                    then "/var/lib/directus-<name>/data.db"
                    else null
                  '';
                  description = mdDoc ''
                    Path to the sqlite3 database file when using sqlite3.
                  '';
                };

                # Caching
                CACHE_ENABLED = mkOption {
                  type = bool;
                  default = instanceCfg.redis.enable;
                  defaultText = literalExpression ''services.directus.<name>.redis.enable'';
                  description = mdDoc ''
                    Whether or not caching is enabled.
                  '';
                };
                CACHE_STORE = mkOption {
                  type = enum ["memory" "redis" "memcache"];
                  default = if instanceCfg.redis.enable then "redis" else "memory";
                  defaultText = literalExpression ''
                    if services.directus.<name>.redis.enable then "redis" else "memory"
                  '';
                  description = mdDoc ''
                    Whether or not caching is enabled.
                  '';
                };
                CACHE_REDIS = mkOption {
                  type = str;
                  default = if instanceCfg.redis.enable then "redis://@127.0.0.1:${redisPort}" else null;
                  defaultText = literalExpression ''
                    if services.directus.<name>.redis.enable
                    then "redis://@127.0.0.1:$${services.directus.<name>.redis.port}"
                    else null
                  '';
                  description = mdDoc ''
                    Whether or not caching is enabled.
                  '';
                };

                # Storage
                STORAGE_LOCATIONS = mkOption {
                  type = str;
                  default = if instanceCfg.useLocalStorage then "local" else null;
                  defaultText = literalExpression ''
                    if services.directus.<name>.useLocalStorage then "local" else null
                  '';
                  description = mdDoc ''
                    A CSV of storage locations (eg: local,digitalocean,amazon) to use.
                    You can use any names you'd like for these keys.
                  '';
                };
                STORAGE_LOCAL_DRIVER = mkOption {
                  type = str;
                  default = if instanceCfg.useLocalStorage then "local" else null;
                  defaultText = literalExpression ''
                    if services.directus.<name>.useLocalStorage then "local" else null
                  '';
                };
                STORAGE_LOCAL_ROOT = mkOption {
                  type = str;
                  default = if instanceCfg.useLocalStorage then "/var/lib/directus-${name}/uploads" else null;
                  defaultText = literalExpression ''
                    if services.directus.<name>.useLocalStorage then "/var/lib/directus-<name>/uploads" else null
                  '';
                };

                # Security
                KEY_FILE = mkOption {
                  type = str;
                  default = "/var/lib/directus-${name}/secrets/key";
                  defaultText = literalExpression "/var/lib/directus-<name>/secrets/key";
                  description = "Unique identifier for the project.";
                };
                SECRET_FILE = mkOption {
                  type = str;
                  default = "/var/lib/directus-${name}/secrets/secret";
                  defaultText = literalExpression "/var/lib/directus-<name>/secrets/secret";
                  description = "Secret string for the project.";
                };

                REFRESH_TOKEN_COOKIE_SECURE = mkOption {
                  type = bool;
                  default = instanceCfg.nginx.virtualHost.forceSSL;
                  defaultText = literalExpression "services.directus.<name>.nginx.virtualHost.forceSSL";
                  description = mdDoc ''
                    Whether or not to use a secure cookie for the refresh token in cookie mode
                  '';
                };
                REFRESH_TOKEN_COOKIE_SAME_SITE = mkOption {
                  type = nullOr (enum ["lax" "strict"]);
                  default = if instanceCfg.nginx.enable then "strict" else null;
                  description = mdDoc ''
                    Value for sameSite in the refresh token cookie when in cookie mode
                  '';
                };

                CORS_ENABLED = mkOption {
                  type = bool;
                  default = instanceCfg.nginx.enable;
                  description = mdDoc ''
                    Whether or not to enable the CORS headers
                  '';
                };
                CORS_ORIGIN = mkOption {
                  type = oneOf [bool str];
                  default = instanceCfg.nginx.enable;
                  description = mdDoc ''
                    Value for the Access-Control-Allow-Origin header.
                    Use true to match the Origin header,
                    or provide a domain or a CSV of domains for specific access
                  '';
                };

                # Extensions
                EXTENSIONS_PATH = mkOption {
                  type = str;
                  default =  "/var/lib/directus-${name}/extensions";
                  description = mdDoc ''
                    Path to your local extensions folder.
                  '';
                };

                # Email
                EMAIL_FROM = mkOption {
                  type = str;
                  default = null;
                  description = mdDoc ''
                    Email address from which emails are sent.
                  '';
                };
                EMAIL_TRANSPORT = mkOption {
                  type = enum ["sendmail", "smtp", "mailgun", "sendgrid", "ses"];
                  default = "sendmail";
                  description = mdDoc ''
                    What to use to send emails.
                  '';
                };
                EMAIL_SENDMAIL_PATH = mkOption {
                  type = path;
                  default = "${pkgs.sendmail}/bin/sendmail";
                  defaultText = literalExpression "$${pkgs.sendmail}/bin/sendmail";
                  description = mdDoc ''
                    Path to your sendmail executable.
                  '';
                };

                # Bootstrap
                ADMIN_EMAIL = mkOption {
                  type = str;
                  default = null;
                  description = mdDoc ''
                    The email address of the first user that will be automatically created.
                  '';
                };
                ADMIN_PASSWORD_FILE = mkOption {
                  type = path;
                  default = null;
                  description = mdDoc ''
                    The file containing the password of the first user that will be automatically created.
                  '';
                };

                # Telemetry
                TELEMETRY = mkOption {
                  type = bool;
                  default = true;
                  description = mdDoc ''
                    Allow Directus to collect anonymized data about your environment.
                  '';
                };

              };
            };
          };

          nginx = mkOption {
            type = submodule (recursiveUpdate (import ../web-servers/nginx/vhost-options.nix { inherit config lib; }) {});
            default = {};
            description = mdDoc ''
                With this option, you can customize the nginx virtualHost settings.
            '';
          };

          redis = {
            type = submodule;
            description = "redis options";
            default = { enable = false; };
            options = {
              enable = mkEnableOption "Enable redis for caching";

              port = mkOption {
                type = port;
                description = "Port used by redis";
              };
            };
          };
        };
      }));
    };
  };

  # Créer 
  # - des options
  #   - choix des 3 dossiers et de la DB (défaut /var/lib/directus-prout)
  #   - choix du port de directus et de redis
  #   - choix d'activer le fail2ban
  #   - choix d'activer le redis
  #   - choix d'activer le nginx
  # - un dossier qui contiendra les sources (/var/lib/directus ?)
  #   - au choix
  # - un user directus-prout,
  # - un service directus-prout,
  #   - je pense que le hardening peut être vénère
  #   - faire une slice pour les directus-* et des règles de CPUShares
  # - un redis-directus-prout,
  #   - possibilité d'utiliser le même pour les différents usages ? je crois selon le docker compose proposé.
  # - un virtual-host nginx
  #   - possibilité de gérer les assets? → node_modules/@directus/app/dist/assets
  # - un fail2ban directus-prout
  # Génération du .env aussi
  # Génération du script de dl directus
  # Export SQL dans /var/backup

  config = let
    cfg = config.services.funkwhale;

    recursiveUpdateArray = sets: builtins.foldl' (s1: s2: lib.recursiveUpdate s1 s2) {} sets;

  in lib.mkIf (any (s: s.enable) cfg.servers)
  (lib.recursiveUpdate
  {
    # Common config
    systemd.services."directus-npm-setup" = {
      enable = true;
      serviceConfig = {
        Type = "oneshot";
        ExecStart = pkgrs.writeScript "directus-npm-start.sh" ''
        '';
      };
    };
  }
  (recursiveUpdateArray (map (config:
    {
      # Instance-specific config

      environment.etc."directus/directus-${name}".text = builtins.toJSON
      # Remove variables set to null
      (lib.filterAttrs (key: value: value != null) settings);

      systemd.services."directus-${name}" = {
        enable = true;
        requires = [ "directus-npm-setup" ];
        after = [ "directus-npm-setup" ];
        serviceConfig = {
          User = "directus-${name}";
          Group = "directus-${name}";
          Environment = [ "CONFIG_PATH=/etc/directus/directus-${name}/config.json" ];
          # Generate secrets and bootstrap application
          ExecStartPre = pkgs.writeScript "directus-${name}-init" ''
            #!${pkgs.runtimeShell}
            genPasswd() {
            ${pkgs.libressl}/bin/openssl rand -base64 40 | tr -cd '[:alnum:]'
            }
            DIR=/var/lib/directus-${name}/secrets
            mkdir -p DIR
            [[ -e $DIR/key ]] || ${pkgs.libossp_uuid}/bin/uuid -v4 > $DIR/key
            [[ -e $DIR/secret ]] || genPasswd > $DIR/secret
            "${cfg.package}/.bin/directus bootstrap";
          '';
          ExecStart = "${cfg.package}/.bin/directus start";
          ReadWritePaths = [ instanceCfg.dataDir instanceCfg.configDir ]
          ++ optionals (instanceCfg.settings.STORAGE_LOCAL_ROOT != null) [ instanceCfg.settings.STORAGE_LOCAL_ROOT ];
          UMask = "0027";
          Restart = "always";
          RestartSec = 10;
          # systemd directory management
          StateDirectory = "/var/lib/directus-${name}";
          StateDirectoryMode = "0750";
          ConfigurationDirectory = "/etc/directus/directus-${name}";
          ConfigurationDirectoryMode = "0750";
          # Security
          LockPersonality = true;
          NoNewPrivileges = true;
          PrivateDevices = true;
          PrivateTmp = true;
          PrivateUsers = true;
          ProtectClock = true;
          ProtectControlGroups = true;
          ProtectHome = true;
          ProtectHostname = true;
          ProtectKernelLogs = true;
          ProtectKernelModules = true;
          ProtectKernelTunables = true;
          ProtectProc = "invisible";
          ProtectSystem = "strict";
          RestrictNamespaces = true;
          RestrictSUIDSGID = true;
        };
      };
    }
    cfg.servers)))
    );
