{ lib, pkgs, config, ... }:
let
  json = pkgs.formats.json {};
  settingsJson = settings: json.generate "config.json" (lib.filterAttrs (key: value: value != null) settings);
in {
  options.services.directus = with lib; with types; {
    enable = mkEnableOption "enable Directus";

    allowDirectusLicense = mkEnableOption ''
      required. Allow-list directus, which has an "unfree but ethical" license.
      See [here](https://github.com/directus/directus/releases/tag/v10.0.0) for more information on the license agreement.
    '';

    package = mkOption {
      type = package;
      description = "The directus package to use";
      default = pkgs.callPackage ../../../pkgs/directus {};
    };

    servers = mkOption {
      default = {};
      description = "Configuration of multiple directus instances";
      type = attrsOf (submodule ({name, config, ...}: {
        options = {

          enable = mkEnableOption "enable this directus instance";

          domain = mkOption {
            type = str;
            description = ''
              Whether to use local storage for file uploads
            '';
          };

          useLocalStorage = mkOption {
            type = bool;
            default = true;
            description = ''
              Whether to use local storage for file uploads
            '';
          };

          settings = mkOption {
            default = {};
            description = ''
              Settings passed to Directus. A config.json file is generated by Nix.

              Setting a value to null will remove it from the config.json
              For example, to override DB_* settings to local postgresql:
              ```nix
              {
                DB_FILENAME = null; # remove DB_FILENAME default-coded value
                DB_CLIENT = "postgres";
                DB_HOST = "localhost";
                DB_PORT = config.services.postgresql.settings.port;
              }
              ```

              See [upstream doc](https://docs.directus.io/self-hosted/config-options.html) for supported options.

              Some options mentionned in this doc are also used by this module (activation script, nginx, redis etc.).
              Changing them also changes related configuration.
            '';
            type = submodule {
              freeformType = (attrsOf (nullOr (oneOf [str int bool]))) // { description = "settings option"; };
              options = {
                # General
                HOST = mkOption {
                  type = str;
                  default = if config.nginx.enable then "127.0.0.1" else "0.0.0.0";
                  defaultText = literalExpression ''if services.directus.servers.<name>.nginx.enable then "127.0.0.1" else "0.0.0.0"'';
                  description = ''
                    IP or host the API listens on
                  '';
                };
                PORT = mkOption {
                  type = port;
                  default = 8055;
                  description = ''
                    The port Directus will run on
                  '';
                };
                PUBLIC_URL = mkOption {
                  type = str;
                  default = if config.nginx.enable
                  then "https://${config.nginx.serverName}${config.nginx.location}"
                  else "/";
                  defaultText = literalExpression ''if config.nginx.enable then config.nginx.serverName + config.nginx.location else "/"'';
                  description = ''
                    The URL where your API can be reached on the web. It is also used for things like OAuth redirects,
                    forgot-password emails, and logos that needs to be publicly available on the internet.
                  '';
                };
                SERVE_APP = mkOption {
                  type = bool;
                  default = true;
                  # default = !config.nginx.enable;
                  defaultText = literalExpression ''!services.directus.servers.<name>.nginx.enable'';
                  description = ''
                    Whether or not to serve the Admin App under /admin.
                  '';
                };

                # Database
                DB_CLIENT = mkOption {
                  type = enum ["postgres" "mysql" "oracledb" "mssql" "sqlite3" "cockroachdb"];
                  default = "sqlite3";
                  description = ''
                    What database client to use.
                  '';
                };
                DB_FILENAME = mkOption {
                  type = nullOr str;
                  default = if config.settings.DB_CLIENT == "sqlite3"
                  then "/var/lib/directus-${name}/data.db"
                  else null;
                  defaultText = literalExpression ''
                    if services.directus.servers.<name>.settings.DB_CLIENT == "sqlite3"
                    then "/var/lib/directus-<name>/data.db"
                    else null
                  '';
                  description = ''
                    Path to the sqlite3 database file when using sqlite3.
                  '';
                };

                # Storage
                STORAGE_LOCATIONS = mkOption {
                  type = str;
                  default = if config.useLocalStorage then "local" else null;
                  defaultText = literalExpression ''
                    if services.directus.servers.<name>.useLocalStorage then "local" else null
                  '';
                  description = ''
                    A CSV of storage locations (eg: local,digitalocean,amazon) to use.
                    You can use any names you'd like for these keys.
                  '';
                };
                STORAGE_LOCAL_DRIVER = mkOption {
                  type = nullOr str;
                  default = if config.useLocalStorage then "local" else null;
                  defaultText = literalExpression ''
                    if services.directus.servers.<name>.useLocalStorage then "local" else null
                  '';
                };
                STORAGE_LOCAL_ROOT = mkOption {
                  type = nullOr str;
                  default = if config.useLocalStorage then "/var/lib/directus-${name}/uploads" else null;
                  defaultText = literalExpression ''
                    if services.directus.servers.<name>.useLocalStorage then "/var/lib/directus-<name>/uploads" else null
                  '';
                };

                # Security
                KEY_FILE = mkOption {
                  type = str;
                  default = "/var/lib/directus-${name}/secrets/key";
                  defaultText = literalExpression "/var/lib/directus-<name>/secrets/key";
                  description = "Unique identifier for the project.";
                };
                SECRET_FILE = mkOption {
                  type = str;
                  default = "/var/lib/directus-${name}/secrets/secret";
                  defaultText = literalExpression "/var/lib/directus-<name>/secrets/secret";
                  description = "Secret string for the project.";
                };

                REFRESH_TOKEN_COOKIE_SECURE = mkOption {
                  type = bool;
                  default = config.nginx.nginx.forceSSL;
                  defaultText = literalExpression "services.directus.servers.<name>.nginx.nginx.forceSSL";
                  description = ''
                    Whether or not to use a secure cookie for the refresh token in cookie mode
                  '';
                };
                REFRESH_TOKEN_COOKIE_SAME_SITE = mkOption {
                  type = nullOr (enum ["lax" "strict"]);
                  default = if config.nginx.enable then "strict" else null;
                  description = ''
                    Value for sameSite in the refresh token cookie when in cookie mode
                  '';
                };

                CORS_ENABLED = mkOption {
                  type = bool;
                  default = config.nginx.enable;
                  description = ''
                    Whether or not to enable the CORS headers
                  '';
                };
                CORS_ORIGIN = mkOption {
                  type = oneOf [bool str];
                  default = config.nginx.enable;
                  description = ''
                    Value for the Access-Control-Allow-Origin header.
                    Use true to match the Origin header,
                    or provide a domain or a CSV of domains for specific access
                  '';
                };

                # Extensions
                EXTENSIONS_PATH = mkOption {
                  type = str;
                  default =  "/var/lib/directus-${name}/extensions";
                  description = ''
                    Path to your local extensions folder.
                  '';
                };

                # Email
                EMAIL_FROM = mkOption {
                  type = nullOr str;
                  default = null;
                  description = ''
                    Email address from which emails are sent.
                  '';
                };
                EMAIL_TRANSPORT = mkOption {
                  type = nullOr (enum ["sendmail" "smtp" "mailgun" "sendgrid" "ses"]);
                  default = null;
                  description = ''
                    What to use to send emails.
                  '';
                };

                # Bootstrap
                ADMIN_EMAIL = mkOption {
                  type = nullOr str;
                  default = null;
                  description = ''
                    The email address of the first user that will be automatically created.
                  '';
                };
                ADMIN_PASSWORD_FILE = mkOption {
                  type = nullOr path;
                  default = null;
                  description = ''
                    The file containing the password of the first user that will be automatically created.
                  '';
                };

                # Telemetry
                TELEMETRY = mkOption {
                  type = bool;
                  default = true;
                  description = ''
                    Allow Directus to collect anonymized data about your environment.
                  '';
                };
              };
            };
          };

          nginx = mkOption {
            default = {};
            description = "nginx options";
            type = submodule {
              options = {
                enable = mkEnableOption "Enable nginx as a reverse proxy";

                nginx = mkOption {
                  # Upstream, this would be a relative path.
                  # Fine as long the main channel is called nixos
                  type = submodule (recursiveUpdate
                  (import /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/web-servers/nginx/vhost-options.nix
                  { inherit config lib; }) {});
                  default = {};
                  description = ''
                    With this option, you can customize the nginx virtualHost settings.
                  '';
                };

                serverName = mkOption {
                  type = nullOr str;
                  description = "nginx server directive";
                };

                location = mkOption {
                  type = str;
                  default = "";
                  description = "nginx server's location to configure as a proxy. no trailing slash.";
                };
              };
            };
          };
        };
      }));
    };
  };

  # TODO Export SQL dans /var/backup
  # TODO reaction

  config = let
    cfg = config.services.directus;
    enabledServers = lib.filterAttrs (name: conf: conf.enable) cfg.servers;
    anyServerEnabled = (lib.any (s: s.enable) (builtins.attrValues cfg.servers));

  in lib.mkIf anyServerEnabled (lib.mkMerge [ {

    assertions = let
      directusPorts = (map (conf: conf.settings.PORT) (builtins.attrValues enabledServers));
      sortedDirectusPorts = (lib.sort (a: b: a < b) directusPorts);
    in [
      {
        assertion = 0 != builtins.foldl' (a: b: if a != b then b else 0) 0 sortedDirectusPorts;
        message = "Every directus instance must have a different port";
      }
    ];

    environment.systemPackages = [ pkgs.nodejs ] ++ (lib.mapAttrsToList (name: conf: (pkgs.writeShellApplication {
      name = "directus-${name}";
      # runtimeInputs = with pkgs; [];
      text = ''
        set +o errexit

        D="directus-${name}"
        if [[ "$USER" != "$D" ]]
        then
          echo "not executed as $D, changing permissions with sudo"
          exec sudo -u "$D" "$0" "$@"
        fi
        
        export CONFIG_PATH=${settingsJson conf.settings}
        cd /var/lib/"$D"
        exec ${cfg.package}/bin/directus "$@"
      '';
    })) enabledServers);

    systemd.slices.system-directus = {
      enable = true;
      description = "Slice designed to contain all Directus-related services";
    };

  } (lib.mkIf cfg.allowDirectusLicense {
    nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [ "directus" ];
  }) {

    assertions = lib.mapAttrsToList (name: conf: {
      assertion = conf.nginx.enable -> conf.nginx.location != null && conf.nginx.serverName != null;
      message = "If you set services.directus.servers.<name>.nginx.enable to true, you must also set nginx.location & nginx.serverName";
    }) enabledServers
    ++ lib.mapAttrsToList (name: conf: {
      assertion = conf.nginx.location != "" -> "/" != builtins.substring (-1 + builtins.stringLength conf.nginx.location) 1 conf.nginx.location;
      message = "services.directus.servers.<name>.nginx.location musn't end with a '/'";
    }) enabledServers ++ [{
      assertion = cfg.allowDirectusLicense || (builtins.hasAttr "allowUnfree" config.nixpkgs.config && config.nixpkgs.config.allowUnfree);
      message = "If you don't nixpkgs.config.allowUnfree, you must at least services.directus.allowDirectusLicense";
    }];

    users.users = lib.mapAttrs' (name: conf: lib.nameValuePair "directus-${name}" {
      description = "System user for the directus instance ${name}";
      isSystemUser = true;
      group = "directus-${name}";
      home = "/var/lib/directus-${name}";
    }) enabledServers;

    users.groups = lib.mapAttrs' (name: conf: lib.nameValuePair "directus-${name}" {}) enabledServers;

    systemd.tmpfiles.rules = let
      localStorageServers = (lib.filterAttrs (name: conf: conf.useLocalStorage) enabledServers);
    in lib.mapAttrsToList (name: conf: "d /var/lib/directus-${name}/secrets   0750 directus-${name} directus-${name} - -") enabledServers
    ++ lib.mapAttrsToList (name: conf: "d ${conf.settings.STORAGE_LOCAL_ROOT} 0750 directus-${name} directus-${name} - -") localStorageServers
    ++ [ "L /nix/var/nix/gcroots/per-user/root/directus-last - - - - ${cfg.package}" ];

    systemd.services = lib.mapAttrs' (name: conf: let
      settings = settingsJson conf.settings;
    in lib.nameValuePair "directus-${name}" {
      enable = true;
      after = [ "network.target" ];
      wantedBy = [ "multi-user.target" ];
      # path = with pkgs; [ nodejs bash ];
      restartTriggers = [ settings ];
      serviceConfig = {
        Slice = "system-directus.slice";
        User  = "directus-${name}";
        Group = "directus-${name}";
        Environment = [ "CONFIG_PATH=${settings}" ];
        ExecStartPre = pkgs.writeShellScript "directus-${name}-init" ''
          set -e
          genPasswd() {
            ${pkgs.libressl}/bin/openssl rand -base64 40 | tr -cd '[:alnum:]'
          }
          [[ -e secrets/key ]] || ${pkgs.libossp_uuid}/bin/uuid -v4 > secrets/key
          [[ -e secrets/secret ]] || genPasswd > secrets/secret
          chmod 600 secrets/secret secrets/key
          ln -sf ${cfg.package}/lib/package.json .
          ${cfg.package}/bin/directus bootstrap
        '';
        ExecStart = "${cfg.package}/bin/directus start";
        UMask = "0027";
        Restart = "no";
        WorkingDirectory = "/var/lib/directus-${name}";
        StateDirectory   = "directus-${name}";
        StateDirectoryMode = "0750";
        LockPersonality = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateMounts = true;
        PrivateTmp = true;
        PrivateUsers = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        ProtectSystem = "strict";
        RemoveIPC = true;
        RestrictNamespaces = true;
        RestrictSUIDSGID = true;
      };
    }) enabledServers;

    services.nginx.virtualHosts = let
      nginxEnabledServers = builtins.attrValues (lib.filterAttrs (name: conf: conf.nginx.enable) enabledServers);
      groupedByServerNameConfs = builtins.groupBy (conf: conf.nginx.serverName) nginxEnabledServers;
    in builtins.mapAttrs (name: confs: {
      enableACME = true;
      forceSSL = true;
      locations = lib.mkMerge (builtins.map (conf: {
        "${conf.nginx.location}/".proxyPass = "http://localhost:${builtins.toString conf.settings.PORT}/";
        "${conf.nginx.location}" = lib.mkIf (conf.nginx.location != "") { return = "302 ${conf.nginx.location}/"; };
      }) confs);
    }) groupedByServerNameConfs;
  }]);
}
