version: '3'

volumes:
  db:
  backups:

networks:
  proxy-tier:

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: nc_pg
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - /var/secrets/nextcloud-suite/db.env

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    container_name: nc_pg_backup
    volumes:
      - backups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - /var/secrets/nextcloud-suite/db.env

  app:
    image: nextcloud:apache
    restart: always
    container_name: nc_app
    ports:
      - 9000:80
    volumes:
      - /data/nextcloud/html:/var/www/html
    env_file:
      - /var/secrets/nextcloud-suite/db.env
    depends_on:
      - db

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    volumes:
      - ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    environment:
      - domain=nuage.ppom.me
      - VIRTUAL_HOST=write.ppom.me
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9980
      - DONT_GEN_SSL_CERT=true
    networks:
      - proxy-tier

  mail:
    image: bytemark/smtp
    container_name: nc_mail
    restart: always
    ports:
      - 25:25
    env_file:
      - /var/secrets/nextcloud-suite/mail.env

